services:
  nginx:
    # Official Nginx Docker image
    image: nginx:alpine

    # Explicit container name for easier reference and service discovery
    container_name: nginx

    # Automatically restart the container if it stops (unless manually stopped)
    restart: unless-stopped

    volumes:
      # Mount custom Nginx configuration
      # Create a nginx.conf file in this directory and uncomment this line
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount custom server configuration
      # Create a conf.d directory with your server configs and uncomment this line
      # - ./conf.d:/etc/nginx/conf.d:ro
      # Mount static files directory
      # Create an html directory with your static files and uncomment this line
      # - ./html:/usr/share/nginx/html:ro

    # Health check to monitor service availability
    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 10s # Check every 10 seconds
      timeout: 5s # Wait up to 5 seconds for response
      retries: 5 # Mark as unhealthy after 5 consecutive failures
      start_period: 10s # Allow 10 seconds for initial startup before checking

    # Expose Nginx port to the host machine
    # Default HTTP port: 80
    # Change the port to match your requirements
    ports:
      - "xxx:80" # HTTP port - replace xxx with your desired port
      # Optional: HTTPS port
      # - "xxx:443"   # HTTPS port - replace xxx with your desired port

    # Optional: Connect to external networks for proxying to other services
    # networks:
    #   - app-network
